(function(){
  'use strict';
  const KEY='alpineRushPro';
  const defaults={mode:'freeride',setup:'racer',quality:'high',motion:'full',volume:.65,units:'metric',music:'random',tutorial:true};
  let settings={...defaults};
  try{settings={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(settings))}catch{}};
  const medals=()=>{try{return JSON.parse(localStorage.getItem('alpineRushMedals')||'{}')}catch{return{}}};
  const career=()=>{try{return{xp:0,level:1,sponsor:'ROOKIE',runs:0,...JSON.parse(localStorage.getItem('alpineRushCareer')||'{}')}}catch{return{xp:0,level:1,sponsor:'ROOKIE',runs:0}}};
  function awardCareer(score,combo){const current=career(),before=current.level;current.xp+=Math.max(40,Math.round(score*.12)+Math.round(combo*35));current.runs++;current.level=Math.min(50,1+Math.floor(current.xp/1800));const sponsors=['ROOKIE','RIDGELINE','NORTHSTAR','SUMMIT CO.','ALPINE ELITE'];current.sponsor=sponsors[Math.min(sponsors.length-1,Math.floor((current.level-1)/5))];localStorage.setItem('alpineRushCareer',JSON.stringify(current));return{...current,leveled:current.level>before,next:current.level*1800,progress:current.xp%1800}};
  const contracts=[{id:'air',label:'LAND 3 TRICKS',stat:'trickCount',target:3,reward:650},{id:'line',label:'TAKE 2 RISK LINES',stat:'riskLines',target:2,reward:800},{id:'patrol',label:'CLEAR 4 PATROL HAZARDS',stat:'patrolClears',target:4,reward:700},{id:'speed',label:'FINISH A DOWNHILL EVENT',stat:'downhill',target:1,reward:900}];
  function contract(){const day=Math.floor(Date.now()/86400000),item=contracts[day%contracts.length];let done=false;try{done=localStorage.getItem(`alpineContract:${day}`)==='done'}catch{}return{...item,day,done}};
  function submitContract(stats){const item=contract(),value=Number(stats[item.stat]||0);if(item.done||value<item.target)return{...item,progress:Math.min(item.target,value),completed:false};try{localStorage.setItem(`alpineContract:${item.day}`,'done')}catch{}return{...item,progress:item.target,completed:true}};
  const badgeDefinitions=[{id:'first-line',name:'FIRST LINE',test:s=>s.runs>=1},{id:'trickster',name:'TRICKSTER',test:s=>s.trickCount>=5},{id:'risk-taker',name:'RISK TAKER',test:s=>s.riskLines>=1},{id:'patrol-proof',name:'PATROL PROOF',test:s=>s.patrolClears>=3},{id:'stash-hunter',name:'STASH HUNTER',test:s=>s.stashFinds>=1},{id:'speed-demon',name:'SPEED DEMON',test:s=>s.mode==='downhill'},{id:'alpine-pass',name:'ALPINE PASS',test:s=>s.routeIndex>=5},{id:'colorado-day',name:'COLORADO DAY',test:s=>s.mode==='colorado'},{id:'fourteener',name:'14ER READY',test:s=>s.routeIndex===2||s.routeIndex===3||s.routeIndex===6||s.routeIndex===7},{id:'bluebird',name:'BLUEBIRD WARRIOR',test:s=>s.mode==='colorado'&&s.trickCount>=2},{id:'last-chair',name:'LAST CHAIR',test:s=>s.runs>=10}];
  const weeklyModifiers=[{id:'no-jump',name:'NO JUMP WEEK',description:'Keep skis and boards grounded.'},{id:'all-patrol',name:'PATROL OVERLOAD',description:'More patrol hazards on every line.'},{id:'max-speed',name:'SEND IT WEEK',description:'Speed builds score faster.'}];
  function weeklyModifier(){const day=Math.floor(Date.now()/86400000),m=weeklyModifiers[Math.floor(day/7)%weeklyModifiers.length];return{...m,week:Math.floor(day/7)}}
  const upgrades=()=>{try{return{edge:0,pop:0,float:0,...JSON.parse(localStorage.getItem('alpineRushUpgrades')||'{}')}}catch{return{edge:0,pop:0,float:0}}};
  function buyUpgrade(type){const u=upgrades();if(u[type]>=3)return u;u[type]++;localStorage.setItem('alpineRushUpgrades',JSON.stringify(u));return u}
  function badges(){try{return JSON.parse(localStorage.getItem('alpineRushBadges')||'{}')}catch{return{}}}
  function awardBadges(stats){const earned=badges(),newBadges=[];badgeDefinitions.forEach(b=>{if(!earned[b.id]&&b.test(stats)){earned[b.id]={name:b.name,date:new Date().toISOString()};newBadges.push(b.name)}});if(newBadges.length)localStorage.setItem('alpineRushBadges',JSON.stringify(earned));return{earned,newBadges,total:badgeDefinitions.length}};
  function awardMedal(id,score,time){const all=medals(),rank=score>=8000?'gold':score>=4500?'silver':'bronze',order={bronze:1,silver:2,gold:3};if(!all[id]||order[rank]>order[all[id].rank])all[id]={rank,score,time,date:new Date().toISOString()};localStorage.setItem('alpineRushMedals',JSON.stringify(all));return rank}
  let audio=null,wind=null,edge=null,master=null;
  function muted(){try{return localStorage.getItem('alpineRushSound')==='off'}catch{return false}}
  function ensureAudio(){if(audio)return audio;try{audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=muted()?0:settings.volume*.16;master.connect(audio.destination);const makeNoise=(type,frequency)=>{const length=audio.sampleRate*2,buffer=audio.createBuffer(1,length,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=Math.random()*2-1;const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=buffer;source.loop=true;filter.type=type;filter.frequency.value=frequency;gain.gain.value=0;source.connect(filter).connect(gain).connect(master);source.start();return{filter,gain}};wind=makeNoise('lowpass',620);edge=makeNoise('bandpass',1450)}catch{}return audio}
  function setRideAudio(active,speed=1,carve=0){ensureAudio();if(!audio)return;const now=audio.currentTime;wind.gain.gain.setTargetAtTime(active?Math.min(.42,.04+speed*.09):0,now,.12);wind.filter.frequency.setTargetAtTime(420+speed*390,now,.15);edge.gain.gain.setTargetAtTime(active?Math.abs(carve)*.22:0,now,.06);master.gain.setTargetAtTime(muted()?0:settings.volume*.16,now,.08)}
  function setSetting(name,value){settings[name]=name==='volume'?Number(value):value;save();document.documentElement.dataset.quality=settings.quality;document.documentElement.dataset.motion=settings.motion;document.documentElement.style.setProperty('--motion-scale',settings.motion==='reduced'?'0':'1');if(master)master.gain.value=settings.volume*.16}
  function drawPreview(canvas,run,route){if(!canvas||!run)return;const dpr=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth||300,h=canvas.clientHeight||150;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,route.sky[0]);g.addColorStop(1,route.snow[0]);c.fillStyle=g;c.fillRect(0,0,w,h);c.strokeStyle='rgba(255,255,255,.18)';c.lineWidth=24;c.lineCap='round';c.beginPath();run.line.forEach((p,i)=>{const x=20+p[1]*(w-40),y=17+p[0]*(h-34);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.strokeStyle=run.difficulty.includes('BLACK')?'#111820':'#58b8ef';c.lineWidth=4;c.beginPath();run.line.forEach((p,i)=>{const x=20+p[1]*(w-40),y=17+p[0]*(h-34);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}
  function gamepad(){const pad=navigator.getGamepads?.()[0];if(!pad)return null;return{steer:Math.abs(pad.axes[0]||0)>.14?pad.axes[0]:0,jump:!!pad.buttons[0]?.pressed,boost:!!pad.buttons[1]?.pressed,pause:!!pad.buttons[9]?.pressed}}
  function registerPWA(){if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
  setSetting('quality',settings.quality);setSetting('motion',settings.motion);registerPWA();
  window.AlpinePro={settings,setSetting,setRideAudio,drawPreview,gamepad,awardMedal,medals,career,awardCareer,contract,submitContract,badges,awardBadges,badgeDefinitions,weeklyModifier,upgrades,buyUpgrade,ensureAudio};
})();
