(function(){
  'use strict';
  const button=document.getElementById('replayButton');
  const playButton=document.getElementById('playReplayButton');
  const relevant=new Set(['ArrowLeft','ArrowRight','a','d','q','e','w','s','Shift',' ','x','Escape']);
  let events=[],markers=[],started=0,recording=false;
  const store=(value)=>{try{localStorage.setItem('alpineRushLastReplay',JSON.stringify(value))}catch{}};
  const start=()=>{events=[];markers=[];started=performance.now();recording=true};
  const stop=()=>{if(!recording)return;recording=false;store({version:1,duration:Math.round(performance.now()-started),events:events.slice(-2500),markers:markers.slice(-80)});};
  new MutationObserver(()=>{const playing=document.getElementById('game')?.classList.contains('playing');if(playing&&!recording)start();if(!playing&&recording)stop()}).observe(document.getElementById('game'),{attributes:true,attributeFilter:['class']});
  addEventListener('keydown',event=>{if(recording&&relevant.has(event.key))events.push([Math.round(performance.now()-started),'down',event.key])});
  addEventListener('keyup',event=>{if(recording&&relevant.has(event.key))events.push([Math.round(performance.now()-started),'up',event.key])});
  button?.addEventListener('click',async()=>{let replay=null;try{replay=JSON.parse(localStorage.getItem('alpineRushLastReplay')||'null')}catch{}if(!replay){button.textContent='NO REPLAY YET';setTimeout(()=>button.textContent='EXPORT REPLAY',1200);return}const encoded=btoa(unescape(encodeURIComponent(JSON.stringify(replay))));try{await navigator.clipboard.writeText(encoded);button.textContent='REPLAY COPIED';setTimeout(()=>button.textContent='EXPORT REPLAY',1400)}catch{button.textContent='COPY BLOCKED';setTimeout(()=>button.textContent='EXPORT REPLAY',1400)}});
  document.getElementById('importReplayButton')?.addEventListener('click',()=>{const code=prompt('Paste a friend ghost code');if(!code)return;try{const trimmed=code.trim();if(trimmed.length>200000)throw new Error('too large');const decoded=decodeURIComponent(escape(atob(trimmed))),replay=JSON.parse(decoded),events=Array.isArray(replay?.events)?replay.events:[];if(!events.length||events.length>2500)throw new Error('invalid events');if(events.some(item=>!Array.isArray(item)||item.length!==3||!Number.isFinite(item[0])||item[0]<0||item[0]>3600000||!['down','up'].includes(item[1])||!relevant.has(item[2])))throw new Error('invalid event');const safe={version:1,duration:Math.min(3600000,Number(replay.duration)||0),events,markers:Array.isArray(replay.markers)?replay.markers.slice(0,80).map(marker=>[Number(marker?.[0])||0,String(marker?.[1]||'').slice(0,32)]):[]};localStorage.setItem('alpineRushLastReplay',JSON.stringify(safe));document.getElementById('importReplayButton').textContent='GHOST IMPORTED';setTimeout(()=>document.getElementById('importReplayButton').textContent='IMPORT GHOST',1400)}catch{document.getElementById('importReplayButton').textContent='INVALID CODE';setTimeout(()=>document.getElementById('importReplayButton').textContent='IMPORT GHOST',1400)}});
  playButton?.addEventListener('click',()=>{let replay=null;try{replay=JSON.parse(localStorage.getItem('alpineRushLastReplay')||'null')}catch{}if(!replay?.events?.length){playButton.textContent='NO REPLAY YET';setTimeout(()=>playButton.textContent='PLAY REPLAY',1200);return}window.AlpinePro?.setSetting('tutorial',false);window.beginCountdown?.();const wait=setInterval(()=>{if(!document.getElementById('game')?.classList.contains('playing'))return;clearInterval(wait);for(const [at,type,keyName] of replay.events)setTimeout(()=>window.dispatchEvent(new KeyboardEvent(type==='down'?'keydown':'keyup',{key:keyName,code:keyName===' '?'Space':keyName,bubbles:true})),at)},100)});
  window.AlpineRushReplay={latest:()=>{try{return JSON.parse(localStorage.getItem('alpineRushLastReplay')||'null')}catch{return null}},mark:(label)=>{if(recording)markers.push([Math.round(performance.now()-started),String(label).slice(0,32)])}};
})();
