/* Alpine Rush WebGL piste renderer. The legacy 2D canvas is retired; HTML HUD/screens remain unchanged. */
(function(){'use strict';const canvas=document.getElementById('worldCanvas');if(!canvas)return;const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)return;
const vs=`attribute vec3 p;attribute vec3 c;uniform mat4 m;varying vec3 v;void main(){gl_Position=m*vec4(p,1.);v=c;}`;const fs=`precision mediump float;varying vec3 v;void main(){gl_FragColor=vec4(v,1.);}`;function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);return s}const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);gl.useProgram(program);const pLoc=gl.getAttribLocation(program,'p'),cLoc=gl.getAttribLocation(program,'c'),mLoc=gl.getUniformLocation(program,'m'),buffer=gl.createBuffer();gl.enable(gl.DEPTH_TEST);
const keys={left:false,right:false,jump:false};addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=true;if(['ArrowRight','d','D'].includes(e.key))keys.right=true;if(e.code==='Space')keys.jump=true});addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=false;if(['ArrowRight','d','D'].includes(e.key))keys.right=false;if(e.code==='Space')keys.jump=false});
let riderX=0,velocity=0,jump=0,jumpV=0,travel=0,last=performance.now(),seed=0;const traffic=[];for(let i=0;i<9;i++)traffic.push({x:(Math.random()-.5)*5,z:-18-i*22,speed:.7+Math.random()*.35,color:i%2?'#e98256':'#58c8da'});
function resize(){const d=Math.min(devicePixelRatio||1,2),w=innerWidth*d,h=innerHeight*d;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h)}addEventListener('resize',resize);resize();
function mul(a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let row=0;row<4;row++)r[c*4+row]=a[row]*b[c*4]+a[4+row]*b[c*4+1]+a[8+row]*b[c*4+2]+a[12+row]*b[c*4+3];return r}function perspective(fovy,aspect,n,f){const q=1/Math.tan(fovy/2),r=new Float32Array(16);r[0]=q/aspect;r[5]=q;r[10]=(f+n)/(n-f);r[11]=-1;r[14]=2*f*n/(n-f);return r}function look(eye,center){const z=norm([eye[0]-center[0],eye[1]-center[1],eye[2]-center[2]]),x=norm(cross([0,1,0],z)),y=cross(z,x),r=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);return r}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function norm(a){const n=Math.hypot(...a)||1;return a.map(v=>v/n)}
function curve(z){return Math.sin((z+travel)*.055)*2.2+Math.sin((z+travel)*.019)*1.1}function addBox(v,x,y,z,w,h,d,color){const c=color,v0=v.length/6;const pts=[[x-w,y,z-d],[x+w,y,z-d],[x+w,y+h,z-d],[x-w,y+h,z-d],[x-w,y,z+d],[x+w,y,z+d],[x+w,y+h,z+d],[x-w,y+h,z+d]],faces=[[0,1,2,0,2,3],[4,6,5,4,7,6],[0,4,5,0,5,1],[3,2,6,3,6,7],[1,5,6,1,6,2],[0,3,7,0,7,4]];faces.flat().forEach(i=>{v.push(...pts[i],...c)});return v0}function addPiste(v){for(let z=10;z>-260;z-=10){const center=curve(z),next=curve(z-10),w=7+Math.max(0,-z)*.012;addBox(v,(center+next)/2,.02,z-5,w,.08,5,[.82,.92,.95]);addBox(v,center-w-5,-.02,z-5,5,.04,5,[.18,.3,.35]);addBox(v,center+w+5,-.02,z-5,5,.04,5,[.18,.3,.35])}}
function addTree(v,x,z){const y=-.02;addBox(v,x,y,z,.18,2.5,.18,[.2,.4,.28]);for(let i=0;i<3;i++)addBox(v,x,y+.6+i*.55,z,.75-i*.14, .55,.7,[.08,.25,.2])}function addSkier(v,x,z,color){addBox(v,x,.18,z,.22,.9,.16,hex(color));addBox(v,x,.98,z,.16,.16,.14,[.04,.1,.13]);addBox(v,x-.32,.05,z,.38,.035,.08,[.9,.96,.98])}function hex(h){const n=parseInt(h.slice(1),16);return[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255]}
function render(now){const dt=Math.min(.04,(now-last)/1000);last=now;const playing=document.querySelector('.game')?.classList.contains('playing');if(playing){velocity+=(keys.right?1:0)*dt*3;velocity-=(keys.left?1:0)*dt*3;velocity*=Math.pow(.08,dt);riderX=Math.max(-5,Math.min(5,riderX+velocity*dt));travel+=dt*(16+Math.abs(velocity)*3);if(keys.jump&&jump===0)jump=.05,jumpV=7;if(jump>0){jumpV-=18*dt;jump+=jumpV*dt;if(jump<=0)jump=0}traffic.forEach(r=>{r.z+=dt*(8+r.speed*5);if(r.z>8)r.z=-260-Math.random()*90;r.x+=(Math.sin((travel+r.z)*.03)*.015)});}
resize();gl.clearColor(.47,.67,.75,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const v=[];addPiste(v);for(let z=-15;z>-250;z-=25){const c=curve(z);addTree(v,c-10,z);addTree(v,c+10,z)}traffic.forEach(r=>addSkier(v,curve(r.z)+r.x,r.z,r.color));addSkier(v,curve(0)+riderX,.18-jump,'#ef7449');gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(pLoc);gl.vertexAttribPointer(pLoc,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(cLoc);gl.vertexAttribPointer(cLoc,3,gl.FLOAT,false,24,12);const aspect=canvas.width/canvas.height,view=look([curve(4)+riderX,3.6,7],[curve(-24)+riderX*.3,1,-24]),matrix=mul(perspective(Math.PI/3,aspect,.1,400),view);gl.uniformMatrix4fv(mLoc,false,matrix);gl.drawArrays(gl.TRIANGLES,0,v.length/6);requestAnimationFrame(render)}requestAnimationFrame(render)})();
