import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const game=fs.readFileSync('game.js','utf8');
const packageJson=JSON.parse(fs.readFileSync('package.json','utf8'));
if(packageJson.scripts?.test!=='npm run check')throw new Error('Missing predictable npm test script');
for(const token of ['aria-live="polite"','aria-label="Activate boost"','aria-label="Front flip"'])if(!html.includes(token))throw new Error(`Missing accessible interaction: ${token}`);
for(const token of ['twitter:card','twitter:image','hero-proof','PLAY YOUR FIRST RUN','application/ld+json'])if(!html.includes(token))throw new Error(`Missing marketability surface: ${token}`);
if(!game.includes('aria-pressed'))throw new Error('Route selection is missing an accessible selected state');
if(!fs.readFileSync('styles.css','utf8').includes('@keyframes impact'))throw new Error('Missing impact feedback styling');
if(!game.includes("game.dataset.surface"))throw new Error('Missing surface presentation state');
if(!fs.readFileSync('styles.css','utf8').includes('.results-screen.new-record'))throw new Error('Missing personal-record presentation state');
if(!game.includes("toast('NEW PERSONAL BEST'"))throw new Error('Missing personal-record celebration');
if(!game.includes("setAttribute('aria-pressed','true')"))throw new Error('Missing pressed-state feedback for held controls');
const assets=['styles.css?v=51','modern.css?v=4','pro-systems.js?v=4','replay.js?v=5','systems/events.js?v=1','systems/audio.js?v=1','systems/input.js?v=1','systems/ui-state.js?v=1','game.js?v=117','performance.js?v=1','mobile.js?v=3'];
for(const asset of assets)if(!html.includes(asset)||!fs.existsSync(asset.split('?')[0]))throw new Error(`Missing production asset: ${asset}`);
const sw=fs.readFileSync('sw.js','utf8');
const leaderboard=fs.readFileSync('leaderboard/server.mjs','utf8');
for(const token of ["const host=process.env.HOST||'127.0.0.1'","/healthz","server.requestTimeout=15000","SIGTERM"])if(!leaderboard.includes(token))throw new Error(`Missing leaderboard operational safeguard: ${token}`);
for(const asset of ['./styles.css?v=51','./modern.css?v=4','./game.js?v=117','./mobile.js?v=3','./pro-systems.js?v=4','./replay.js?v=5','./systems/events.js?v=1','./systems/audio.js?v=1','./systems/input.js?v=1','./systems/ui-state.js?v=1','./performance.js?v=1','./assets/resorts/keystone.webp','./assets/resorts/cooper.webp','./assets/resorts/copper-mountain.webp'])if(!sw.includes(`'${asset}'`))throw new Error(`Asset is not cached offline: ${asset}`);
for(const token of ['AlpineRushEvents','AlpineRushAudio','AlpineRushInput'])if(!game.includes(token))throw new Error(`Missing architecture seam: ${token}`);
if(!fs.existsSync('leaderboard.md'))throw new Error('Missing leaderboard contract');
if(!fs.existsSync('leaderboard/server.mjs'))throw new Error('Missing leaderboard service');
if(!sw.includes("./game.js?v=117"))throw new Error('Service worker is not caching the current game build');
for(const token of ['FINAL SEQUENCE','finaleClears','finaleCourseLength','finaleModeObjective','finaleFeature:o.feature'])if(!game.includes(token))throw new Error(`Missing finale regression guard: ${token}`);
console.log('Alpine Rush production checks passed');
